fix: ami - handle missing RootDeviceName (#230)
some of the Canonical images don't have a RootDeviceName and threw

KeyError: 'RootDeviceName'

so we now handle this edge case