fix: describe when key is missing (#378)
fixes KeyError when key is missing from instance, eg: an instance without a keypair
```
 ec2 describe -c InstanceId,State,Name,Type,DnsName,LaunchTime,KeyName
Traceback (most recent call last):
  File "/Users/tekumara/.local/bin/aec", line 8, in <module>
    sys.exit(main())
  File "/Users/tekumara`/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/main.py", line 196, in main
    result, output_format = cli.dispatch(build_parser(), args)
  File "/Users/tekumara/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/util/cli.py", line 103, in dispatch
    return (call_me(**vars(pargs)), output_format)
  File "/Users/tekumara/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/command/ec2.py", line 214, in describe
    desc[col] = i[col]
KeyError: 'KeyName'
```