fix: handle missing ExecutionTime
fixes

❯ ssm compliance-summary
Traceback (most recent call last):
  File "/Users/tekumara/.local/bin/aec", line 8, in <module>
    sys.exit(main())
  File "/Users/tekumara/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/main.py", line 241, in main
    display.pretty_print(result, output_format)
  File "/Users/tekumara/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/util/display.py", line 77, in pretty_print
    first = next(result)
  File "/Users/tekumara/.local/pipx/venvs/aec-cli/lib/python3.9/site-packages/aec/command/ssm.py", line 112, in compliance_summary
    "Last operation time": i["ExecutionSummary"]["ExecutionTime"],
KeyError: 'ExecutionTime'