install wheel into venv (#196)
On a clean install (ie: empty *~/.cache/pip/wheels/*) wheels will need to be built. In this scenario `make install` errors with:
```
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyjq
```

Because the virtualenv created by `venv` does not install `wheel` [by design](https://bugs.python.org/issue30628#msg295844):
> It should also be noted that wheel is not installed by venv and must also be installed after the environment creation if needed.

This PR fixes this.