fix: NameError: name 'UtilizationMetricTypeDef' is not defined (#297)
`from __future__ import annotations` will [treat annotations as strings at runtime](https://adamj.eu/tech/2021/05/15/python-type-hints-future-annotations/)

This fixes:
```
$ aec co over-provisioned
Traceback (most recent call last):
  File "/Users/tekumara/code/aec/.venv/bin/aec", line 33, in <module>
    sys.exit(load_entry_point('aec-cli', 'console_scripts', 'aec')())
  File "/Users/tekumara/code/aec/src/aec/main.py", line 134, in main
    result = cli.dispatch(build_parser(), args)
  File "/Users/tekumara/code/aec/src/aec/util/cli.py", line 87, in dispatch
    return call_me(**vars(pargs))
  File "/Users/tekumara/code/aec/src/aec/command/compute_optimizer.py", line 17, in over_provisioned
    def util(metric: UtilizationMetricTypeDef) -> str:
NameError: name 'UtilizationMetricTypeDef' is not defined
```

It also enables use of the Python 3.10 union type shorthand,ie:
`InstanceTypeDef | VolumeTypeDef` instead of `Union[InstanceTypeDef, VolumeTypeDef]`