refactor: empty string identifier guard again (#497)
before:
```
❯ aec ec2 terminate ""
Traceback (most recent call last):
  File "/Users/oliver.mannion/code/aec/.venv/bin/aec", line 10, in <module>
    sys.exit(main())
  File "/Users/oliver.mannion/code/aec/src/aec/main.py", line 233, in main
    result, output_format = cli.dispatch(build_parser(), args)
  File "/Users/oliver.mannion/code/aec/src/aec/util/cli.py", line 105, in dispatch
    return (call_me(**vars(pargs)), output_format)
  File "/Users/oliver.mannion/code/aec/src/aec/command/ec2.py", line 476, in terminate
    raise ValueError("Missing instance identifier")
ValueError: Missing instance identifier
```

after:
```
❯ aec ec2 terminate ""
usage: aec ec2 terminate [-h] [--config CONFIG] [-o {table,csv}] ident
aec ec2 terminate: error: argument ident: is empty string
```

also simplifies the code