feat: nicer error message for NoRegionError (#459)
Instead of a stacktrace now shows:
```
NoRegionError: You must specify a region..

Authenticate with the appropriate AWS role before retrying.
```